name: CMake Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: kaya-berk/ExcelParser

      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'

      - name: Install CMake & tools
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make ninja-build

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_PREFIX_PATH=$Qt5_DIR

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure

      - name: Secret Scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git -v
