name: CMake Build & Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ExcelParser code
        uses: actions/checkout@v4
        with:
          repository: kaya-berk/ExcelParser
          fetch-depth: 0

      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'

      - name: Install CMake & tools
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make ninja-build

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_PREFIX_PATH=$Qt5_DIR

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure

  git-leaks:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout ExcelParser code
        uses: actions/checkout@v4
        with:
          repository: kaya-berk/ExcelParser
          fetch-depth: 0

      - name: Secret Scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          config: .gitleaks.toml

  sca-dependency-check:
    runs-on: ubuntu-latest
    needs: git-leaks
    steps:
      - name: Checkout ExcelParser code
        uses: actions/checkout@v4
        with:
          repository: kaya-berk/ExcelParser
          fetch-depth: 0

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "ExcelParser"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/

  codeql-analysis:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest
    needs: sca-dependency-check
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout ExcelParser code
        uses: actions/checkout@v4
        with:
          repository: kaya-berk/ExcelParser
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
